# AI Agent Persona Schedule
# Defines when AI should be synchronous (Elf) vs asynchronous (Night Owl)

project: "holoscript-scientific-plugin"
owner: "Josep"
timezone: "America/Los_Angeles"  # Adjust to your timezone

# AI reads this file to determine current behavior mode
# Update this file to change AI behavior patterns

schedule:
  # Weekdays: 9-6 collaborative (Elf), off-hours autonomous (Night Owl)
  monday-friday:

    # Working hours: Interactive, collaborative
    working-hours:
      time: "9:00-18:00"
      persona: elf
      description: "Synchronous companion - real-time collaboration"

      tools:
        - vscode-claude-extension
        - claude-desktop
        - antigravity-interactive
        - cursor

      behavior:
        interactive: true
        wait-for-approval: true
        batch-questions: false        # Ask immediately
        interrupt-allowed: true       # Can interrupt Josep's work
        create-pr: true               # Create PRs for review
        auto-merge: false             # Never auto-merge during work hours

      focus:
        - pair-programming
        - real-time suggestions
        - immediate feedback
        - tactical decisions

    # After hours: Autonomous execution
    after-hours:
      time: "18:00-9:00"
      persona: night-owl
      description: "Asynchronous helper - works independently overnight"

      tools:
        - github-actions
        - claude-api-batch
        - antigravity-autonomous
        - automated-workflows

      behavior:
        interactive: false
        wait-for-approval: false      # Execute pre-approved work
        batch-questions: true         # Save questions for morning
        interrupt-allowed: false      # No notifications
        create-pr: true
        auto-merge: false             # Create PR, don't merge

      constraints:
        - no-breaking-changes
        - all-tests-must-pass
        - all-quality-gates-pass
        - no-database-migrations
        - no-production-deploys
        - work-only-on-approved-tasks  # Check .ai-decisions.md

      focus:
        - implement-approved-features
        - write-tests
        - generate-documentation
        - refactor-for-quality
        - research-and-prepare-proposals

  # Weekends: Low-priority autonomous work only
  saturday-sunday:
    all-day:
      time: "0:00-23:59"
      persona: night-owl
      description: "Weekend mode - experimental/low-priority work"

      tools:
        - github-actions
        - automated-workflows

      behavior:
        interactive: false
        wait-for-approval: false
        batch-questions: true
        interrupt-allowed: false
        priority-filter: low          # Only low-priority tasks
        create-pr: true
        auto-merge: false

      constraints:
        - experimental-ok             # Can try new approaches
        - non-urgent-only
        - no-production-deploys
        - no-critical-path-work

      focus:
        - technical-debt-cleanup
        - documentation-improvements
        - performance-optimizations
        - research-spikes
        - prototype-new-ideas

# Emergency override (checked first before schedule)
emergency-mode:
  enabled: false
  reason: ""                          # e.g., "Production outage - urgent fix needed"
  until: ""                           # ISO timestamp when to revert
  persona: elf                        # Override to Elf (24/7 interactive)
  notify:
    - josep@email.com
    - slack-channel-emergency

# Decision sprint times (when Josep reviews AI work)
decision-sprints:
  sprint-1:
    time: "9:00-10:00"
    focus: "Strategic decisions, overnight work review, set morning priorities"
  sprint-2:
    time: "12:00-13:00"
    focus: "Tactical decisions, morning work review, set afternoon priorities"
  sprint-3:
    time: "17:00-17:30"
    focus: "Daily retrospective, set overnight autonomous tasks"

# Notification preferences
notifications:
  during-working-hours:
    urgent: true                      # Critical errors, blockers
    questions: true                   # AI needs decisions
    progress: false                   # Batch progress updates

  after-hours:
    urgent: true                      # Only critical issues
    questions: false                  # Batch for morning
    progress: false                   # No notifications

  weekends:
    urgent: true                      # Only critical issues
    questions: false
    progress: false

# Context refresh strategy
context-refresh:
  trigger: "event-driven"             # Refresh on git events, not schedule
  max-staleness: "30-minutes"         # Force refresh if context older than this
  sources:
    - .ai-decisions.md
    - .ai-context-stream.jsonl
    - git-log (last 20 commits)
    - open-prs
    - ci-cd-status

# Quality enforcement
quality-gates:
  enforce: true
  gates:
    - linting
    - type-checking
    - complexity-analysis
    - security-scanning
    - test-coverage

  on-failure:
    action: "block-commit"            # Don't allow commit if quality gates fail
    notify: true

# Last updated
last-updated: "2026-02-13T00:00:00Z"
version: "1.0"
